### ISSUE TITLE
AprilTag Pose2d Localization

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2023#1]
Be able to return a Pose2d object, given the output from AprilTags code. Pose2d should reflect robot's position.

Also hard-code in Pose2d's of all 8 AprilTags on the field

**Comment by ebay-kid** [comment]
https://github.com/wpilibsuite/allwpilib/pull/4124/files

This should have all the needed utility methods.

However, AprilTags code will likely need to be implemented manually on the new co-processor

**Comment by ebay-kid** [comment]
https://github.com/wpilibsuite/allwpilib/blob/main/wpimath/src/main/java/edu/wpi/first/math/ComputerVisionUtil.java

**Comment by maxchen132** [comment]
Comment on this issue if you are working on it, thanks!

**Comment by qilsklo** [comment]
I'm working on this

**Comment by ebay-kid** [comment]
Hard-coding should be put into PositionConstants in https://github.com/FRCteam3952/FRC2023/blob/main/src/main/java/frc/robot/Constants.java

**Comment by ebay-kid** [comment]
https://firstfrc.blob.core.windows.net/frc2023/FieldAssets/2023LayoutMarkingDiagram.pdf

Has the locations of all tags

**Comment by qilsklo** [comment]
This is done

**Comment by ebay-kid** [comment]
Completed (the actual implementation is on the Jetson)
