### ISSUE TITLE
Arm Movement Specification (controller)

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2023#12]
Driver relative

Forward stick: extend as power
6 button: down to pick up
Trigger button: close claw hold down to keep closing
7 button: open claw
Pull back stick: return to start config (N)
Left/right stick: turn turret
5: claw palm moves to left side (90deg cap)
4: claw palm moves to right side (90deg cap)
3: claw horizontal

**Comment by bobandjoe** [comment]
currently working on stuff rn

**Comment by ebay-kid** [comment]
Max is working on this I think

**Comment by maxchen132** [comment]
Comment on this issue if you are working on it, thanks!

**Comment by maxchen132** [comment]
I think this is tentatively done, will have test the implementation before closing this issue

**Comment by maxchen132** [comment]
Closed tentatively
