### ISSUE TITLE
Implement April tags individually (separate codebase)

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2023#14]
This will be run on a Jetson Xavier (hopefully) but since we're running multiple simultaneous pipelines, photon vision won't work.

https://github.com/NVIDIA-ISAAC-ROS/isaac_ros_apriltag

Here is a potential impl of April tags we can use, though I'm not sure if it supports 16h5 tagset (the one we use), so that should be checked

**Comment by maxchen132** [comment]
Comment on this issue if you are working on it, thanks!

**Comment by ebay-kid** [comment]
I'm working on this right now, it's in https://github.com/FRCteam3952/FRC2023_Vision

**Comment by ebay-kid** [comment]
Completed in https://github.com/SeanSon2005/AprilTags
