### ISSUE TITLE
Implement Automatic Object Placement

### ISSUE THREAD

**Issue by maxchen132** [FRCteam3952/FRC2023#15]
You may have to look up or ask for information about the game field to properly do this one.

You can assume that we can get the robot to any specific apriltag (see game manual for game field). When the robot is at any specific apriltag, we want preset configurations for the robot to place objects on the poles/platforms for scoring. These measurements should be the same for each apriltag because their surrounding grids are identical. There is a `setIntendedCoordinates()` method that sets the arm to a specific coordinate relative to the center of the robot, measured in inches. Find the coordinates of each pole/platform relative to the center of the robot, assuming it is up against an apriltag, and implement a command to be able to move the arm to each position (using `setIntendedCoordinates()`). You can store the numerical coordinate values in the Constants.java file.

Comment on this issue if you are working on it, thanks!

**Comment by maxchen132** [comment]
https://firstfrc.blob.core.windows.net/frc2023/Manual/2023FRCGameManual.pdf

This is the link to the game manual, it may help with finding measurements. See pg 25 for a visual of the apriltag and its surrounding poles/platforms (which all together is called a grid). Assume that the robot can be positioned directly before the apriltag.

**Comment by maxchen132** [comment]
Put in some structure for this to make it easier to code:

PositionConstants class in Constants.java holds the claw positions for each of the the poles and platforms in the grid (see game manual for reference), relative to (0, 0 ,0) at the center of the robot (assumed to be docked in front of the april tag).

AutomaticObjectPlacementCommand.java is a template class which can be used for the implementation for the automatic object placement command.

If there are any questions, feel free to ask.

**Comment by maxchen132** [comment]
Drawing of grid with specific measurements

https://firstfrc.blob.core.windows.net/frc2023/FieldAssets/TeamVersions/Drawings/TE-23001-Grid-Dwg.pdf

**Comment by siIverfish** [comment]
I will help with the constants.

**Comment by baconman125** [comment]
workin on it

**Comment by maxchen132** [comment]
Closed for now, may return to it later
