### ISSUE TITLE
Implement automatic claw rotation for cones

### ISSUE THREAD

**Issue by maxchen132** [FRCteam3952/FRC2023#16]
We will have a camera mounted on the claw, pointing in the direction which the claw faces. Assume we can get the orientation angle (in degrees) of the cone from camera vision, where the angle is 0 when the tip of the cone points vertically upwards from the camera's perspective. Implement automatic claw rotation in which the claw automatically rotates to match the orientation angle of the cone.

Comment if you are taking this issue, thanks!

**Comment by maxchen132** [comment]
Added `autoRotate()` function to `ClawRotationSubsystem.java` and bound it to a button number constant in `RobotContainer.java` to make this issue easier to take. `autoRotate()` still needs to be implemented per the specifications above.

**Comment by siIverfish** [comment]
ima do it

**Comment by maxchen132** [comment]
Basis of function has been implemented
