### ISSUE TITLE
Implement smooth travel and turning onto a Tank Drive (field oriented drive)

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2023#2]
Normally, tank drive can only go forwards and backwards, with turning as separate controls. We want to be able to turn the robot and move it with the same joystick. Ex: if the robot is currently pointed forward and the joystick is pulled to the right 90 degrees, the robot will keep moving and turn to the right until it is at 90 degrees and keep moving.

**Comment by siIverfish** [comment]
ok guys dw i totally got this

**Comment by ebay-kid** [comment]
Done
