### ISSUE TITLE
Add claw limit switch

### ISSUE THREAD

**Issue by ebay-kid** [FRCteam3952/FRC2023#43]
There's a limit switch on the claw, when the limit is pressed then the claw should stop closing and the encoder value should be set to the initial value (aka MIN_GRIP_ENCODER_VALUE)

**Comment by Cybertron51** [comment]
derek peng doing

**Comment by maxchen132** [comment]
Tentatively implemented, switching to pneumatics, so changes may have to be made later

**Comment by ebay-kid** [comment]
Since we have pneumatics we don't actually need a limit switch, so I'm closing this for now. Code will be removed soon ™️
